all:
  children:
    mobile_base:
      hosts:
        robot:
          ansible_host: 10.42.0.138
          ansible_user: ngenator
    controller:
      hosts:
        laptop:
          ansible_host: localhost
          ansible_connection: local