all:
  children:
    mobile_base:
      hosts:
        robot:
          ansible_host: 192.168.98.234
          ansible_user: ngenator
          ansible_python_interpreter: /usr/bin/python3
    controller:
      hosts:
        controller:
          ansible_host: localhost
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3