# Note: Make sure to use group_vars/* for actual variables, these are host vars

all:
  children:
    # Variables are defined in group_vars/mobile_base/*
    mobile_base:
      hosts:
        robot:
          ansible_host: 192.168.98.234
          ansible_user: ngenator
          ansible_connection: ssh
          ansible_python_interpreter: /usr/bin/python3
    # Variables are defined in group_vars/controller/*
    controller:
      hosts:
        laptop:
          ansible_host: localhost
          ansible_user: ngenator
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3