- name: install realsense packages
  block:
  - name: add intel signing key
    apt_key:
      keyserver: keys.gnupg.net
      id: 7DCC6F0F

  - name: add intel realsense repo
    apt_repository:
      repo: deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial main
      filename: 'realsense-public'
      state: present
      update_cache: yes

  - name: install realsense packages
    apt:
      name: "{{ item }}"
      state: latest
      allow_unauthenticated: yes
    with_items:
      - realsense-uvcvideo
      - librealsense2-utils
  become: true