- name: install realsense packages
  become: true
  block:
  - name: add intel signing key
    apt_key:
      keyserver: keys.gnupg.net
      id: F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE
  
  - name: add other signing key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE

  - name: add intel realsense repo
    apt_repository:
      repo: "deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo {{ ansible_distribution_release }} main"
      filename: realsense-public
      state: present
      update_cache: yes

  - name: install realsense packages
    apt:
      name: "{{ item }}"
      state: latest
      allow_unauthenticated: yes
    with_items:
      - librealsense2-dkms
      - librealsense2-utils
      - librealsense2-dev
